#!/bin/bash

########################
# for daliy apt update #
########################

# apt update
sudo apt update && sudo apt-get update

# apt upgrade
sudo apt upgrade -y

# remove unused dependencies
sudo apt autoremove --purge -y

# clean partial packages
sudo apt autoclean -y

# cleanup apt cache
sudo apt clean

# autoclean
sudo apt autoclean
